const lessonData = {};

lessonData["01_TheAshCloud.mp3"] = [{
    text: "Maria was a scientist studying a volcano. She thought it was safe, but the volcano exploded suddenly. A huge cloud of hot ash and rock came down the mountain. Maria jumped into her truck and drove fast. The ash cloud turned the day into night. She could not see the road. The engine stopped because of the dust. She had to get out and run. The air was hot and poisonous. She put a wet cloth over her mouth to breathe. She ran until she found a small cave to hide in. She waited there until the ash settled. A rescue team found her covered in gray dust.",
    dict: { "scientist": "bilim insanı", "volcano": "yanardağ", "safe": "güvenli", "exploded": "patladı", "suddenly": "aniden", "huge": "kocaman", "cloud": "bulut", "hot": "sıcak", "ash": "kül", "rock": "kaya", "mountain": "dağ", "jumped": "atladı", "truck": "kamyon", "drove": "sürdü", "fast": "hızlı", "day": "gündüz/gün", "night": "gece", "could not": "yapamadı", "see": "görmek", "road": "yol", "engine": "motor", "stopped": "durdu", "because of": "yüzünden", "dust": "toz", "get out": "dışarı çıkmak", "run": "koşmak", "air": "hava", "poisonous": "zehirli", "put": "koydu", "wet": "ıslak", "cloth": "kumaş/bez", "mouth": "ağız", "breathe": "nefes almak", "ran": "koştu", "until": "kadar", "found": "buldu", "small": "küçük", "cave": "mağara", "hide": "saklanmak", "waited": "bekledi", "there": "orada", "settled": "çöktü/oturdu", "rescue": "kurtarma", "team": "ekip", "covered": "kaplı", "gray": "gri" },
    questions: [ {q:"Was Maria a scientist?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the volcano explode suddenly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she drive a car?", a_en:"No", a_tr:"Hayır"}, {q:"Did the engine stop because of water?", a_en:"No", a_tr:"Hayır"}, {q:"Did she hide in a cave?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the air poisonous?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a rescue team find her?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_TheBigWave.mp3"] = [{
    text: "Sari was playing on a beach in Thailand. She saw the ocean water pull back very far. It looked strange. Then, a massive wall of water came back. It was a tsunami. The water hit the land with great power. Sari grabbed a palm tree and climbed up. The water destroyed houses and carried cars away below her. She held onto the tree for hours. Debris and wood hit her legs, but she did not let go. She was scared she would fall into the fast water. When the water finally went down, she was safe but alone. Her family found her later at a safe zone on a hill.",
    dict: { "playing": "oynayan", "beach": "plaj", "ocean": "okyanus", "water": "su", "pull back": "geri çekilmek", "far": "uzak", "strange": "garip", "massive": "muazzam", "wall": "duvar", "came back": "geri geldi", "tsunami": "tsunami", "hit": "çarptı", "land": "kara", "great": "büyük", "power": "güç", "grabbed": "yakaladı", "palm": "palmiye", "tree": "ağaç", "climbed up": "yukarı tırmandı", "destroyed": "yok etti", "houses": "evler", "carried": "taşıdı", "cars": "arabalar", "below": "aşağıda", "held onto": "tutundu", "hours": "saatler", "debris": "enkaz", "wood": "odun/ahşap", "legs": "bacaklar", "let go": "bırakmak", "scared": "korkmuş", "fall": "düşmek", "fast": "hızlı", "finally": "sonunda", "went down": "aşağı indi", "safe": "güvenli", "alone": "yalnız", "family": "aile", "later": "daha sonra", "zone": "bölge", "hill": "tepe" },
    questions: [ {q:"Was Sari playing on a mountain?", a_en:"No", a_tr:"Hayır"}, {q:"Did the water pull back far?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the massive wave a tsunami?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she climb a palm tree?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she let go of the tree?", a_en:"No", a_tr:"Hayır"}, {q:"Was she alone when the water went down?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her family find her later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_TheDeepDark.mp3"] = [{
    text: "Luis was the boss of a copper mine. He worked with 32 other men deep underground. One day, the mine collapsed. A lot of rock blocked the exit. The men were trapped in a small safety room. It was hot, dark, and dusty. They only had food for two days. Luis became a strong leader. He told the men to eat only one spoon of tuna every two days to make the food last. They waited in the dark for 17 days. They did not know if help was coming. Finally, a drill broke through the ceiling. The men sent a note up that said, 'We are all okay.' Rescuers drilled a bigger hole and saved them.",
    dict: { "boss": "patron", "copper": "bakır", "mine": "maden", "worked": "çalıştı", "men": "adamlar", "deep": "derin", "underground": "yeraltı", "day": "gün", "collapsed": "çöktü", "lot": "çok", "rock": "kaya", "blocked": "engelledi", "exit": "çıkış", "trapped": "kapana kısılmış", "safety": "güvenlik", "room": "oda", "hot": "sıcak", "dark": "karanlık", "dusty": "tozlu", "food": "yiyecek", "strong": "güçlü", "leader": "lider", "told": "söyledi", "eat": "yemek", "spoon": "kaşık", "tuna": "ton balığı", "make": "yapmak", "last": "sürmek/dayanmak", "waited": "beklediler", "know": "bilmek", "help": "yardım", "coming": "geliyor", "drill": "matkap", "broke through": "kırıp geçti", "ceiling": "tavan", "sent": "gönderdi", "note": "not", "rescuers": "kurtarıcılar", "drilled": "deldi", "bigger": "daha büyük", "hole": "delik", "saved": "kurtardı" },
    questions: [ {q:"Was Luis the boss of a copper mine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mine collapse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have food for a month?", a_en:"No", a_tr:"Hayır"}, {q:"Did Luis tell the men to eat tuna?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wait for 17 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a drill break through the ceiling?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they saved?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_TheDrift.mp3"] = [{
    text: "Arthur loved the ocean. He was sailing around the world alone on his boat. One night, something large hit his boat in the middle of the Atlantic Ocean. The boat sank very fast. Arthur jumped into a small rubber raft. He only had a speargun and a little bit of water. He floated on the ocean for 76 days. The sun was very hot, and he was always thirsty. He had a machine to make fresh water from salt water, but it broke often. He had to fix it with old parts to survive. Big fish hit the bottom of his raft, and sharks swam nearby. He saw big ships, but they did not see him. Finally, fishermen saw birds flying around his raft and found him.",
    dict: { "loved": "sevdi", "ocean": "okyanus", "sailing": "seyreden", "around": "etrafında", "world": "dünya", "alone": "yalnız", "boat": "tekne", "night": "gece", "something": "bir şey", "large": "büyük", "hit": "çarptı", "middle": "orta", "sank": "battı", "fast": "hızlı", "jumped": "atladı", "small": "küçük", "rubber": "kauçuk/lastik", "raft": "sal", "speargun": "zıpkın", "little": "biraz", "bit": "parça", "water": "su", "floated": "yüzdü/süzüldü", "days": "günler", "sun": "güneş", "hot": "sıcak", "thirsty": "susamış", "machine": "makine", "make": "yapmak", "fresh": "taze", "salt": "tuz", "broke": "kırıldı/bozuldu", "often": "sık sık", "fix": "tamir etmek", "old": "eski", "parts": "parçalar", "survive": "hayatta kalmak", "big": "büyük", "fish": "balık", "bottom": "alt/dip", "sharks": "köpekbalıkları", "swam": "yüzdü", "nearby": "yakınlarda", "ships": "gemiler", "fishermen": "balıkçılar", "birds": "kuşlar", "flying": "uçan", "found": "buldu" },
    questions: [ {q:"Was Arthur sailing alone?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his boat sink?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he float for 76 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a machine to make fresh water?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the machine break often?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the big ships see him?", a_en:"No", a_tr:"Hayır"}, {q:"Did fishermen find him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_TheFallenCity.mp3"] = [{
    text: "Elena was working in her office in a tall building. Suddenly, the ground shook violently. It was a massive earthquake. The building collapsed. Elena woke up in the dark. She was trapped under heavy concrete and metal. She could not move her legs. The air was full of dust, and it was hard to breathe. She had no water. She heard other people crying, but then they stopped. She found a metal pipe near her head. She used a rock to hit the pipe three times every hour. She did this for two days. Firefighters heard the noise and dug through the rocks to pull her out.",
    dict: { "working": "çalışan", "office": "ofis", "tall": "uzun", "building": "bina", "suddenly": "aniden", "ground": "yer", "shook": "sallandı", "violently": "şiddetle", "massive": "muazzam", "earthquake": "deprem", "collapsed": "çöktü", "woke up": "uyandı", "dark": "karanlık", "trapped": "kapana kısılmış", "under": "altında", "heavy": "ağır", "concrete": "beton", "metal": "metal", "could not": "yapamadı", "move": "hareket ettirmek", "legs": "bacaklar", "air": "hava", "full": "dolu", "dust": "toz", "hard": "zor", "breathe": "nefes almak", "heard": "duydu", "people": "insanlar", "crying": "ağlayan", "stopped": "durdu", "pipe": "boru", "near": "yakın", "head": "kafa", "used": "kullandı", "rock": "kaya", "hit": "çarpmak/vurmak", "times": "kez", "every": "her", "hour": "saat", "firefighters": "itfaiyeciler", "noise": "gürültü", "dug": "kazdı", "pull out": "dışarı çekmek" },
    questions: [ {q:"Was Elena working in a tall building?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there a massive earthquake?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she trapped under wood?", a_en:"No", a_tr:"Hayır"}, {q:"Did she use a rock to hit a pipe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she hit the pipe three times every hour?", a_en:"Yes", a_tr:"Evet"}, {q:"Did firefighters hear the noise?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they dig through the rocks to save her?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_TheFrozenIsland.mp3"] = [{
    text: "Captain James led a team to cross Antarctica. Their ship got stuck in thick ice and sank. The 28 men camped on the floating ice for months. When the ice melted, they used small lifeboats to go to a rocky island. It was cold and empty. James knew nobody would find them there. He took five men and one small boat. They sailed 800 miles across the most dangerous ocean in the world. They fought huge waves and strong winds for weeks. They reached a station on South Georgia Island. James returned with a rescue ship to save the rest of his crew. All the men survived.",
    dict: { "Captain": "Kaptan", "led": "yönetti/önderlik etti", "team": "ekip", "cross": "geçmek", "ship": "gemi", "got stuck": "sıkıştı", "thick": "kalın", "ice": "buz", "sank": "battı", "men": "adamlar", "camped": "kamp yaptı", "floating": "yüzen", "months": "aylar", "melted": "eridi", "used": "kullandı", "lifeboats": "cankurtaran botları", "go": "gitmek", "rocky": "kayalık", "island": "ada", "cold": "soğuk", "empty": "boş", "knew": "biliyordu", "nobody": "hiç kimse", "find": "bulmak", "there": "orada", "took": "aldı", "five": "beş", "small": "küçük", "boat": "tekne", "sailed": "yelken açtı", "miles": "miller", "across": "karşısına", "most": "en", "dangerous": "tehlikeli", "ocean": "okyanus", "world": "dünya", "fought": "savaştı", "huge": "kocaman", "waves": "dalgalar", "strong": "güçlü", "winds": "rüzgarlar", "weeks": "haftalar", "reached": "ulaştı", "station": "istasyon", "returned": "geri döndü", "rescue": "kurtarma", "save": "kurtarmak", "rest": "geri kalan", "crew": "mürettebat", "survived": "hayatta kaldı" },
    questions: [ {q:"Did Captain James lead a team to cross Antarctica?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their ship sink?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they camp on floating ice?", a_en:"Yes", a_tr:"Evet"}, {q:"Did James take five men in a small boat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they sail across a safe ocean?", a_en:"No", a_tr:"Hayır"}, {q:"Did he return with a rescue ship?", a_en:"Yes", a_tr:"Evet"}, {q:"Did all the men survive?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_TheGreatBear.mp3"] = [{
    text: "Hugh was a hunter in the deep forest. He surprised a mother bear and her cubs. The bear attacked him. It bit his leg and broke his ribs. Hugh pretended to be dead. The bear left him. Hugh was badly hurt and could not walk. He was miles from his camp. His friends were too far ahead to hear him. He had to crawl on the ground. He was in great pain. He ate berries and drank water from puddles. He crawled for five days. He had to hide from wolves. Finally, he reached a river and floated down on a log until his friends found him.",
    dict: { "hunter": "avcı", "deep": "derin", "forest": "orman", "surprised": "şaşırttı", "mother": "anne", "bear": "ayı", "cubs": "yavrular", "attacked": "saldırdı", "bit": "ısırdı", "leg": "bacak", "broke": "kırdı", "ribs": "kaburgalar", "pretended": "numara yaptı", "dead": "ölü", "left": "bıraktı", "badly": "kötü bir şekilde", "hurt": "yaralı", "walk": "yürümek", "miles": "miller", "camp": "kamp", "friends": "arkadaşlar", "far": "uzak", "ahead": "ileride", "hear": "duymak", "crawl": "emeklemek", "ground": "yer/zemin", "great": "büyük", "pain": "acı", "ate": "yedi", "berries": "meyveler", "drank": "içti", "water": "su", "puddles": "su birikintileri", "days": "günler", "hide": "saklanmak", "wolves": "kurtlar", "finally": "sonunda", "reached": "ulaştı", "river": "nehir", "floated": "yüzdü/süzüldü", "log": "kütük", "until": "kadar", "found": "buldu" },
    questions: [ {q:"Was Hugh a hunter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear break his ribs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pretend to be dead?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he walk?", a_en:"No", a_tr:"Hayır"}, {q:"Did he crawl for five days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he float down a river on a log?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his friends find him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_TheHighWater.mp3"] = [{
    text: "Ken lived in a city near a big river. It rained for a week. The dam broke, and water rushed into the city. The water rose very fast, filling the first floor of his house. Ken climbed to the second floor, but the water kept rising. He had to climb out the window onto the roof. It was raining hard and very cold. He had no food. He watched cars floating by. He was afraid the house would wash away. He waved a red shirt at helicopters, but they were busy. He spent two nights on the roof. Finally, a neighbor with a boat came and took him to dry land.",
    dict: { "lived": "yaşadı", "city": "şehir", "near": "yakın", "big": "büyük", "river": "nehir", "rained": "yağmur yağdı", "week": "hafta", "dam": "baraj", "broke": "kırıldı/yıkıldı", "water": "su", "rushed": "hücum etti", "rose": "yükseldi", "fast": "hızlı", "filling": "dolduran", "first": "ilk", "floor": "kat", "house": "ev", "climbed": "tırmandı", "second": "ikinci", "kept": "devam etti", "rising": "yükselme", "window": "pencere", "onto": "üzerine", "roof": "çatı", "hard": "sert/şiddetli", "cold": "soğuk", "food": "yiyecek", "watched": "izledi", "cars": "arabalar", "floating": "yüzen", "by": "yanından", "afraid": "korkmuş", "wash away": "sürüklenip gitmek", "waved": "salladı", "red": "kırmızı", "shirt": "gömlek", "helicopters": "helikopterler", "busy": "meşgul", "spent": "geçirdi", "nights": "geceler", "neighbor": "komşu", "boat": "tekne", "came": "geldi", "took": "götürdü/aldı", "dry": "kuru", "land": "kara" },
    questions: [ {q:"Did it rain for a week?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dam break?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Ken climb onto the roof?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a lot of food?", a_en:"No", a_tr:"Hayır"}, {q:"Did he wave a red shirt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did helicopters save him?", a_en:"No", a_tr:"Hayır"}, {q:"Did a neighbor with a boat save him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_TheIcePocket.mp3"] = [{
    text: "Thomas was a cook on a big boat. Early in the morning, a big wave hit the boat. It turned over and sank to the bottom of the ocean. Thomas was in the bathroom. He was thrown around in the dark water. Luckily, he found an air pocket in a cabin. This was a small space with air, but he was trapped underwater. He sat there for 60 hours. It was freezing cold and pitch black. He could hear fish eating nearby. He tried to stay calm to save oxygen. He did not know if anyone was coming. Divers came to find dead bodies, but Thomas grabbed a diver's hand. The diver was shocked. They helped Thomas swim to the surface safely.",
    dict: { "cook": "aşçı", "big": "büyük", "boat": "tekne", "early": "erken", "morning": "sabah", "wave": "dalga", "hit": "çarptı", "turned over": "ters döndü", "sank": "battı", "bottom": "alt/dip", "ocean": "okyanus", "bathroom": "banyo", "thrown": "fırlatıldı", "dark": "karanlık", "water": "su", "luckily": "neyse ki", "found": "buldu", "air": "hava", "pocket": "cep/boşluk", "cabin": "kabin", "small": "küçük", "space": "alan/boşluk", "trapped": "kapana kısılmış", "underwater": "sualtı", "sat": "oturdu", "there": "orada", "hours": "saatler", "freezing": "dondurucu", "cold": "soğuk", "pitch": "zifiri", "black": "siyah", "hear": "duymak", "fish": "balık", "eating": "yiyen", "nearby": "yakınlarda", "tried": "denedi", "stay": "kalmak", "calm": "sakin", "save": "kurtarmak/korumak", "oxygen": "oksijen", "know": "bilmek", "anyone": "kimse", "coming": "geliyor", "divers": "dalgıçlar", "dead": "ölü", "bodies": "bedenler", "grabbed": "yakaladı/tuttu", "hand": "el", "shocked": "şok olmuş", "helped": "yardım etti", "swim": "yüzmek", "surface": "yüzey", "safely": "güvenle" },
    questions: [ {q:"Was Thomas a cook?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a big wave hit the boat?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he in the bathroom?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he find an air pocket?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he trapped for 60 hours?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he grab a diver's hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the diver help him swim to the surface?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_TheLastOneLeft.mp3"] = [{
    text: "Elara joined an expedition to the Arctic to earn money. She was the only woman with four men. They went to a lonely island, but their supply ship never came. They ran out of food. Three men left to walk across the frozen sea for help, but they never returned. The last man got sick and died, leaving Elara all alone. She was scared, but she had to survive. She learned how to use a gun to hunt seals for food. She also had to scare away dangerous polar bears that came near her tent. She lived alone for two years. Finally, a ship arrived and found her alive and healthy.",
    dict: { "joined": "katıldı", "expedition": "keşif", "earn": "kazanmak", "money": "para", "only": "sadece", "woman": "kadın", "four": "dört", "men": "adamlar", "went": "gitti", "lonely": "yalnız", "island": "ada", "supply": "erzak/ikmal", "ship": "gemi", "never": "asla", "came": "geldi", "ran out": "tükendi", "food": "yiyecek", "three": "üç", "left": "ayrıldı", "walk": "yürümek", "across": "karşısına/boyunca", "frozen": "donmuş", "sea": "deniz", "help": "yardım", "returned": "geri döndü", "last": "son", "man": "adam", "got sick": "hastalandı", "died": "öldü", "leaving": "bırakarak", "all": "tüm", "alone": "yalnız", "scared": "korkmuş", "survive": "hayatta kalmak", "learned": "öğrendi", "use": "kullanmak", "gun": "silah", "hunt": "avlamak", "seals": "foklar", "scare away": "korkutup kaçırmak", "dangerous": "tehlikeli", "polar": "kutup", "bears": "ayılar", "near": "yakın", "tent": "çadır", "lived": "yaşadı", "years": "yıllar", "finally": "sonunda", "arrived": "vardı", "found": "buldu", "alive": "canlı", "healthy": "sağlıklı" },
    questions: [ {q:"Was Elara the only woman on the expedition?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the supply ship arrive on time?", a_en:"No", a_tr:"Hayır"}, {q:"Did three men walk across the frozen sea?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the last man die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she learn to hunt seals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she live alone for two years?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she healthy when the ship arrived?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_TheLonelyIsland.mp3"] = [{
    text: "Tom was a fisherman working alone near the Pacific islands. A terrible storm destroyed his boat. He grabbed a piece of wood and floated to a tiny, empty island. He was completely alone. He had no food and no tools. His challenge was to find fresh water. He learned to break coconuts to drink the milk. He also had to make a fire without matches to stay warm at night. He felt very lonely and talked to a volleyball he found on the beach to stay sane. He lived there for four years. One day, a plane saw the smoke from his fire and sent a boat to rescue him.",
    dict: { "fisherman": "balıkçı", "working": "çalışan", "alone": "yalnız", "near": "yakın", "islands": "adalar", "terrible": "korkunç", "storm": "fırtına", "destroyed": "yok etti", "boat": "tekne", "grabbed": "tuttu/yakaladı", "piece": "parça", "wood": "odun/ahşap", "floated": "yüzdü/süzüldü", "tiny": "minik", "empty": "boş", "island": "ada", "completely": "tamamen", "food": "yiyecek", "tools": "aletler", "challenge": "zorluk/meydan okuma", "find": "bulmak", "fresh": "taze", "water": "su", "learned": "öğrendi", "break": "kırmak", "coconuts": "hindistan cevizleri", "drink": "içmek", "milk": "süt", "make": "yapmak", "fire": "ateş", "without": "olmadan", "matches": "kibritler", "stay": "kalmak", "warm": "sıcak", "night": "gece", "felt": "hissetti", "lonely": "yalnız", "talked": "konuştu", "volleyball": "voleybol topu", "beach": "plaj", "sane": "aklı başında", "lived": "yaşadı", "there": "orada", "years": "yıllar", "day": "gün", "plane": "uçak", "saw": "gördü", "smoke": "duman", "sent": "gönderdi", "rescue": "kurtarmak" },
    questions: [ {q:"Was Tom a fisherman?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a storm destroy his boat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he float to a tiny island?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he drink coconut milk?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make a fire with matches?", a_en:"No", a_tr:"Hayır"}, {q:"Did he talk to a volleyball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a plane see the smoke from his fire?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_TheRedDirt.mp3"] = [{
    text: "The Smith family was driving across the Australian Outback. It was a very empty and hot place. Their car engine broke down. They were hundreds of miles from the nearest town. There was no phone signal. The father knew they should not leave the car because the car is easier to see from the sky. They had only two bottles of water. The heat was dangerous, over 40 degrees. They sat under the car for shade. They waited for four days. They were very weak. Finally, a plane flying overhead saw the sun reflecting off their car mirror and sent help.",
    dict: { "family": "aile", "driving": "süren", "across": "boyunca", "empty": "boş", "hot": "sıcak", "place": "yer", "car": "araba", "engine": "motor", "broke down": "bozuldu", "hundreds": "yüzlerce", "miles": "miller", "nearest": "en yakın", "town": "kasaba", "phone": "telefon", "signal": "sinyal", "father": "baba", "knew": "biliyordu", "should not": "yapmamalı", "leave": "ayrılmak", "easier": "daha kolay", "see": "görmek", "sky": "gökyüzü", "two": "iki", "bottles": "şişeler", "water": "su", "heat": "ısı/sıcaklık", "dangerous": "tehlikeli", "over": "üzerinde", "degrees": "dereceler", "sat": "oturdular", "under": "altında", "shade": "gölge", "waited": "beklediler", "days": "günler", "weak": "zayıf", "finally": "sonunda", "plane": "uçak", "flying": "uçan", "overhead": "baş üstünde", "sun": "güneş", "reflecting": "yansıyan", "off": "üzerinden", "mirror": "ayna", "sent": "gönderdi", "help": "yardım" },
    questions: [ {q:"Was the family driving in the Australian Outback?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their car engine break down?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have a phone signal?", a_en:"No", a_tr:"Hayır"}, {q:"Did the father want to leave the car?", a_en:"No", a_tr:"Hayır"}, {q:"Did they sit under the car for shade?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wait for four days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a plane see the sun reflecting off their mirror?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_TheRisingWater.mp3"] = [{
    text: "A soccer coach and 12 young boys went to explore a cave. It was a fun trip, but then it started to rain very hard outside. Water rushed into the cave. The group ran deeper inside to find dry ground. They were trapped on a small rock shelf. The water blocked the exit. They had no food and only flashlights. The air was getting thin. The coach taught the boys how to meditate to stay calm and save energy. They sat there for nine days in the dark. British divers found them. It took many days to teach the boys how to dive underwater to get out.",
    dict: { "soccer": "futbol", "coach": "antrenör", "young": "genç", "boys": "erkek çocuklar", "went": "gitti", "explore": "keşfetmek", "cave": "mağara", "fun": "eğlenceli", "trip": "gezi", "started": "başladı", "rain": "yağmur", "hard": "şiddetli", "outside": "dışarıda", "water": "su", "rushed": "hücum etti", "into": "içine", "group": "grup", "ran": "koştu", "deeper": "daha derin", "inside": "içeri", "find": "bulmak", "dry": "kuru", "ground": "yer/zemin", "trapped": "kapana kısılmış", "small": "küçük", "rock": "kaya", "shelf": "raf/çıkıntı", "blocked": "engelledi", "exit": "çıkış", "food": "yiyecek", "only": "sadece", "flashlights": "el fenerleri", "air": "hava", "getting": "oluyordu", "thin": "ince/az", "taught": "öğretti", "meditate": "meditasyon yapmak", "stay": "kalmak", "calm": "sakin", "save": "korumak/tasarruf etmek", "energy": "enerji", "sat": "oturdu", "days": "günler", "dark": "karanlık", "British": "İngiliz", "divers": "dalgıçlar", "found": "buldu", "took": "aldı/sürdü", "many": "birçok", "teach": "öğretmek", "dive": "dalmak", "underwater": "sualtı", "get out": "çıkmak" },
    questions: [ {q:"Did a soccer coach and 12 boys explore a cave?", a_en:"Yes", a_tr:"Evet"}, {q:"Did water rush into the cave?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they trapped on a rock shelf?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have a lot of food?", a_en:"No", a_tr:"Hayır"}, {q:"Did the coach teach the boys to meditate?", a_en:"Yes", a_tr:"Evet"}, {q:"Did British divers find them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have to dive underwater to get out?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_TheRiverPath.mp3"] = [{
    text: "Maya was a 17-year-old student. She flew with her mother over the Amazon jungle. Suddenly, lightning hit the plane. It broke apart in the sky. Maya fell into the trees, which saved her life. She woke up alone and hurt. Everyone else was dead. She remembered her father’s advice: 'If you are lost, follow the river to find people.' She walked for 11 days in the deep jungle. She had cuts on her arms, and insects laid eggs in her wounds. It was very painful. She saw crocodiles in the water but kept walking. She was very hungry and tired. Finally, she found a small boat and waited. Workers found her the next day and took her to a hospital.",
    dict: { "year-old": "yaşında", "student": "öğrenci", "flew": "uçtu", "mother": "anne", "over": "üzerinden", "jungle": "orman", "suddenly": "aniden", "lightning": "şimşek/yıldırım", "hit": "çarptı", "plane": "uçak", "broke apart": "parçalandı", "sky": "gökyüzü", "fell": "düştü", "trees": "ağaçlar", "saved": "kurtardı", "life": "hayat", "woke up": "uyandı", "alone": "yalnız", "hurt": "yaralı", "everyone": "herkes", "else": "başka", "dead": "ölü", "remembered": "hatırladı", "advice": "tavsiye", "lost": "kayıp", "follow": "takip etmek", "river": "nehir", "find": "bulmak", "people": "insanlar", "walked": "yürüdü", "days": "günler", "deep": "derin", "cuts": "kesikler", "arms": "kollar", "insects": "böcekler", "laid": "bıraktı/yumurtladı", "eggs": "yumurtalar", "wounds": "yaralar", "painful": "acı verici", "saw": "gördü", "crocodiles": "timsahlar", "water": "su", "kept": "devam etti", "walking": "yürümeye", "hungry": "aç", "tired": "yorgun", "small": "küçük", "boat": "tekne", "waited": "bekledi", "workers": "işçiler", "next": "sonraki", "day": "gün", "took": "götürdü", "hospital": "hastane" },
    questions: [ {q:"Was Maya 17 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Did lightning hit the plane?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the trees save her life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her father tell her to follow the river?", a_en:"Yes", a_tr:"Evet"}, {q:"Did insects lay eggs in her wounds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she see crocodiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did workers take her to a hospital?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_TheSafariGuide.mp3"] = [{
    text: "David was a tour guide in Africa. He was driving his jeep alone to check a trail. The jeep got stuck in deep mud. He could not move it. Night came, and he heard lions roaring. He was far from the camp. He did not have a gun, only a knife. The lions smelled him and circled the jeep. They tried to bite the tires. David had to stay inside the open jeep. He did not sleep all night. He was thirsty and terrified. The next day, the sun was very hot. He waited for two days with the lions nearby. Finally, another guide saw his tire tracks and came to rescue him.",
    dict: { "tour": "tur", "guide": "rehber", "driving": "süren", "jeep": "cip", "alone": "yalnız", "check": "kontrol etmek", "trail": "patika/iz", "got stuck": "sıkıştı", "deep": "derin", "mud": "çamur", "could not": "yapamadı", "move": "hareket ettirmek", "night": "gece", "came": "geldi", "heard": "duydu", "lions": "aslanlar", "roaring": "kükreyen", "far": "uzak", "camp": "kamp", "gun": "silah", "only": "sadece", "knife": "bıçak", "smelled": "kokusunu aldı", "circled": "etrafını sardı", "tried": "denedi", "bite": "ısırmak", "tires": "lastikler", "stay": "kalmak", "inside": "içinde", "open": "açık", "sleep": "uyumak", "all": "tüm", "thirsty": "susamış", "terrified": "dehşete düşmüş", "next": "sonraki", "day": "gün", "sun": "güneş", "hot": "sıcak", "waited": "bekledi", "days": "günler", "nearby": "yakınlarda", "finally": "sonunda", "another": "başka bir", "saw": "gördü", "tire": "lastik", "tracks": "izler", "rescue": "kurtarmak" },
    questions: [ {q:"Was David a tour guide?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his jeep get stuck in mud?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a gun?", a_en:"No", a_tr:"Hayır"}, {q:"Did lions circle the jeep?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sleep all night?", a_en:"No", a_tr:"Hayır"}, {q:"Did he stay in the jeep for two days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did another guide see his tire tracks?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_TheSandstormRunner.mp3"] = [{
    text: "Giovanni was a police officer who loved running. He joined a long race across the Sahara Desert. On the fourth day, a bad sandstorm started. The wind blew sand everywhere, and Giovanni could not see. He lost the trail. He kept running, but he went the wrong way. He ran out of water quickly. He was lost in the hot desert for nine days. He was so thirsty that he caught bats in an old building and drank their blood. He also drank his own urine. He wanted to die, but he kept walking. He lost 33 pounds. Finally, he found a camp of nomadic people. They gave him milk and saved him.",
    dict: { "police": "polis", "officer": "memur", "loved": "sevdi", "running": "koşmayı", "joined": "katıldı", "long": "uzun", "race": "yarış", "across": "boyunca", "Desert": "Çöl", "fourth": "dördüncü", "day": "gün", "bad": "kötü", "sandstorm": "kum fırtınası", "started": "başladı", "wind": "rüzgar", "blew": "estirdi/üfledi", "sand": "kum", "everywhere": "her yer", "could not": "yapamadı", "see": "görmek", "lost": "kaybetti", "trail": "patika/iz", "kept": "devam etti", "went": "gitti", "wrong": "yanlış", "way": "yol", "ran out": "tükendi", "water": "su", "quickly": "hızlıca", "hot": "sıcak", "days": "günler", "thirsty": "susamış", "caught": "yakaladı", "bats": "yarasalar", "old": "eski", "building": "bina", "drank": "içti", "blood": "kan", "also": "ayrıca", "own": "kendi", "urine": "idrar", "wanted": "istedi", "die": "ölmek", "walking": "yürümeye", "pounds": "pound (ağırlık)", "finally": "sonunda", "found": "buldu", "camp": "kamp", "nomadic": "göçebe", "people": "insanlar", "gave": "verdi", "milk": "süt", "saved": "kurtardı" },
    questions: [ {q:"Was Giovanni a police officer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a bad sandstorm start?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he run out of water quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he drink bat blood?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he drink his own urine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lose 33 pounds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did nomadic people give him milk?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_TheSnowTrap.mp3"] = [{
    text: "Sarah and John were driving home for Christmas. A heavy blizzard started. The snow fell very fast. Their car slid off the road and into a ditch. They could not get out. The snow covered the whole car. They were trapped inside. It was freezing. They knew they could not run the engine all the time because they would run out of gas or get poisoned. They ran the car for ten minutes every hour to get warm. They had no food, only some candy. They huddled together for three days. A snowplow driver saw the antenna of their car sticking out of the snow and dug them out.",
    dict: { "driving": "süren", "home": "eve", "heavy": "şiddetli/ağır", "blizzard": "kar fırtınası", "started": "başladı", "snow": "kar", "fell": "düştü/yağdı", "fast": "hızlı", "car": "araba", "slid off": "kayıp çıktı", "road": "yol", "into": "içine", "ditch": "hendek", "could not": "yapamadı", "get out": "çıkmak", "covered": "kapladı", "whole": "bütün", "trapped": "kapana kısılmış", "inside": "içinde", "freezing": "dondurucu", "knew": "biliyordu", "run": "çalıştırmak", "engine": "motor", "all": "tüm", "time": "zaman", "because": "çünkü", "ran out": "tükendi", "gas": "benzin", "get": "olmak", "poisoned": "zehirlenmiş", "ran": "çalıştırdı", "minutes": "dakikalar", "every": "her", "hour": "saat", "warm": "sıcak", "food": "yiyecek", "only": "sadece", "candy": "şeker", "huddled": "sokuldular/büzüştüler", "together": "birlikte", "days": "günler", "snowplow": "kar küreme", "driver": "sürücü", "saw": "gördü", "antenna": "anten", "sticking out": "dışarı çıkan", "dug out": "kazıp çıkardı" },
    questions: [ {q:"Were Sarah and John driving home for Christmas?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their car slide into a ditch?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snow cover the whole car?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they run the engine all the time?", a_en:"No", a_tr:"Hayır"}, {q:"Did they have a lot of food?", a_en:"No", a_tr:"Hayır"}, {q:"Did they huddle together for three days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a snowplow driver see their antenna?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_TheStoneGrip.mp3"] = [{
    text: "Leo loved adventure. He went hiking alone in a narrow canyon in Utah. While he was climbing down, a big rock moved. It fell and trapped his right arm against the canyon wall. Leo could not move. He had very little water and no food. He stood in the same spot for five days. He yelled for help, but nobody heard him. He drank his own urine because he was so thirsty. He knew he would die there. So, Leo made a brave and scary decision. He used a small, dull knife to cut off his own arm. He was free. He climbed down a cliff with one hand and walked six miles. A family on a hike found him.",
    dict: { "loved": "sevdi", "adventure": "macera", "went": "gitti", "hiking": "doğa yürüyüşü", "alone": "yalnız", "narrow": "dar", "canyon": "kanyon", "climbing": "tırmanan", "down": "aşağı", "big": "büyük", "rock": "kaya", "moved": "hareket etti", "fell": "düştü", "trapped": "sıkıştırdı", "right": "sağ", "arm": "kol", "against": "karşı", "wall": "duvar", "could not": "yapamadı", "move": "hareket etmek", "little": "az", "water": "su", "food": "yiyecek", "stood": "durdu", "same": "aynı", "spot": "nokta", "days": "günler", "yelled": "bağırdı", "help": "yardım", "nobody": "hiç kimse", "heard": "duydu", "drank": "içti", "own": "kendi", "urine": "idrar", "because": "çünkü", "thirsty": "susamış", "knew": "biliyordu", "die": "ölmek", "there": "orada", "so": "bu yüzden", "made": "yaptı", "brave": "cesur", "scary": "korkutucu", "decision": "karar", "used": "kullandı", "small": "küçük", "dull": "kör/keskin olmayan", "knife": "bıçak", "cut off": "kesti", "free": "özgür", "climbed": "tırmandı", "cliff": "uçurum", "hand": "el", "walked": "yürüdü", "miles": "miller", "family": "aile", "hike": "yürüyüş", "found": "buldu" },
    questions: [ {q:"Was Leo hiking alone in a canyon?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a rock trap his arm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he stand in the same spot for five days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did somebody hear him yell?", a_en:"No", a_tr:"Hayır"}, {q:"Did he cut off his own arm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use a sharp knife?", a_en:"No", a_tr:"Hayır"}, {q:"Did a family find him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_TheVoid.mp3"] = [{
    text: "Simon and Joe were climbing a high mountain in Peru. On the way down, Joe fell and broke his leg. Simon tried to lower Joe down with a rope. But Joe slipped over a cliff edge and hung in the air during a storm. Simon could not pull him up. To save himself, Simon cut the rope. Joe fell deep into a hole in the ice called a crevasse. Simon thought Joe was dead. But Joe was alive on a small ledge. He could not climb up, so he lowered himself deeper into the dark hole. He found a way out at the bottom. He crawled for three days with a broken leg and no food. He reached the camp just before Simon left.",
    dict: { "climbing": "tırmanan", "high": "yüksek", "mountain": "dağ", "way": "yol", "down": "aşağı", "fell": "düştü", "broke": "kırdı", "leg": "bacak", "tried": "denedi", "lower": "indirmek", "rope": "ip", "slipped": "kaydı", "over": "üzerinden", "cliff": "uçurum", "edge": "kenar", "hung": "asıldı", "air": "hava", "during": "sırasında", "storm": "fırtına", "could not": "yapamadı", "pull up": "yukarı çekmek", "save": "kurtarmak", "himself": "kendisini", "cut": "kesti", "deep": "derin", "hole": "delik", "ice": "buz", "called": "adlandırılan", "crevasse": "buzul çatlağı", "thought": "düşündü", "dead": "ölü", "alive": "canlı", "small": "küçük", "ledge": "çıkıntı", "climb up": "yukarı tırmanmak", "so": "bu yüzden", "lowered": "indirdi", "deeper": "daha derin", "dark": "karanlık", "found": "buldu", "out": "dışarı", "bottom": "alt/dip", "crawled": "emekledi", "days": "günler", "broken": "kırık", "food": "yiyecek", "reached": "ulaştı", "camp": "kamp", "just": "tam", "before": "önce", "left": "ayrıldı" },
    questions: [ {q:"Were Simon and Joe climbing a mountain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Joe break his leg?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Simon cut the rope?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Joe fall into a crevasse?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Joe dead?", a_en:"No", a_tr:"Hayır"}, {q:"Did he crawl for three days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he reach the camp before Simon left?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_TheWallOfFire.mp3"] = [{
    text: "Jack was camping in a national park. He smelled smoke. Suddenly, a huge forest fire appeared over the hill. The fire moved faster than a car. Jack tried to run to his car, but the fire blocked the road. He was surrounded by flames and thick smoke. He could not breathe well. He saw a river nearby. He jumped into the water and covered his head with a wet jacket. The fire burned the trees all around him. The heat was intense. He stayed in the water for five hours until the fire passed. A ranger found him the next morning.",
    dict: { "camping": "kamp yapan", "national": "ulusal", "park": "park", "smelled": "kokusunu aldı", "smoke": "duman", "suddenly": "aniden", "huge": "kocaman", "forest": "orman", "fire": "yangın", "appeared": "belirdi/ortaya çıktı", "over": "üzerinde", "hill": "tepe", "moved": "hareket etti", "faster": "daha hızlı", "than": "den/dan", "car": "araba", "tried": "denedi", "run": "koşmak", "blocked": "engelledi", "road": "yol", "surrounded": "kuşatılmış", "flames": "alevler", "thick": "kalın/yoğun", "could not": "yapamadı", "breathe": "nefes almak", "well": "iyi", "saw": "gördü", "river": "nehir", "nearby": "yakınlarda", "jumped": "atladı", "water": "su", "covered": "kapladı", "head": "kafa", "wet": "ıslak", "jacket": "ceket", "burned": "yaktı", "trees": "ağaçlar", "all": "tüm", "around": "etrafında", "heat": "ısı", "intense": "yoğun/şiddetli", "stayed": "kaldı", "hours": "saatler", "until": "kadar", "passed": "geçti", "ranger": "korucu", "found": "buldu", "next": "sonraki", "morning": "sabah" },
    questions: [ {q:"Was Jack camping in a national park?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fire move faster than a car?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fire block the road to his car?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he jump into a river?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he cover his head with a wet jacket?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the heat intense?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a ranger find him the next morning?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_TheWhiteSilence.mp3"] = [{
    text: "Marcus and Elias were on a university sports team. They flew over snowy mountains in a small plane to play a game. Suddenly, the wind pushed the plane down, and it crashed into the snow. Many of their friends died in the crash. The survivors had no warm clothes and very little food. It was extremely cold. They waited for help, but nobody came. After ten days, they heard on a radio that the police stopped looking for them. They were starving. Elias made a very hard choice to eat the bodies of their dead friends to stay alive. Later, a large amount of snow fell on their plane. Marcus and Elias knew they had to move. They walked for 12 days across the dangerous mountains without climbing equipment. Finally, they saw a farmer and asked for help. Helicopters came the next day.",
    dict: { "university": "üniversite", "sports": "spor", "team": "takım", "flew": "uçtu", "over": "üzerinden", "snowy": "karlı", "mountains": "dağlar", "small": "küçük", "plane": "uçak", "play": "oynamak", "game": "oyun", "suddenly": "aniden", "wind": "rüzgar", "pushed": "itti", "down": "aşağı", "crashed": "çarptı", "snow": "kar", "many": "birçok", "friends": "arkadaşlar", "died": "öldü", "crash": "kaza", "survivors": "hayatta kalanlar", "warm": "sıcak", "clothes": "kıyafetler", "very": "çok", "little": "az", "food": "yiyecek", "extremely": "son derece", "cold": "soğuk", "waited": "beklediler", "help": "yardım", "nobody": "hiç kimse", "came": "geldi", "after": "sonra", "days": "günler", "heard": "duydu", "radio": "radyo", "police": "polis", "stopped": "durdu/bıraktı", "looking": "aramayı", "starving": "açlıktan ölmek", "made": "yaptı", "hard": "zor", "choice": "seçim", "eat": "yemek", "bodies": "bedenler", "dead": "ölü", "stay": "kalmak", "alive": "canlı", "later": "daha sonra", "large": "büyük", "amount": "miktar", "fell": "düştü", "knew": "biliyordu", "had to": "zorundaydı", "move": "hareket etmek", "walked": "yürüdüler", "across": "boyunca", "dangerous": "tehlikeli", "without": "olmadan", "climbing": "tırmanma", "equipment": "ekipman", "finally": "sonunda", "saw": "gördü", "farmer": "çiftçi", "asked": "istedi", "helicopters": "helikopterler", "next": "sonraki", "day": "gün" },
    questions: [ {q:"Were Marcus and Elias on a sports team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their small plane crash?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the survivors have warm clothes?", a_en:"No", a_tr:"Hayır"}, {q:"Did the police stop looking for them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they eat the bodies of dead friends?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they walk for 12 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a farmer help them?", a_en:"Yes", a_tr:"Evet"} ]
}];
